### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by bsuth** [FishBallSandwich/flappy_emmies_scripts#1]
https://github.com/FishBallSandwich/flappy_emmies_scripts/blob/0a5203e296d949efbe980d824cd42a3008528b08/FinishLine.cs#L30

cutscene is one word

**Comment by FishBallSandwich** [comment]
This PR addressed the reported issue: [https://github.com/FishBallSandwich/flappy_emmies_scripts/pull/2](url)
